sonar.projectKey=yuhangzzzz_rapp-tycoon-backend
sonar.organization=yuhangzzzz
sonar.projectName=rApp Tycoon Backend
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/package-info.java,**/*Application.java
