CREATE TABLE game_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    basestation_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
    description TEXT,
    impact_health DECIMAL(5,2) DEFAULT 0.00,
    impact_customer_experience DECIMAL(5,2) DEFAULT 0.00,
    impact_cost DECIMAL(10,2) DEFAULT 0.00,
    impact_energy_efficiency DECIMAL(5,2) DEFAULT 0.00,
    impact_automation_reliability DECIMAL(5,2) DEFAULT 0.00,
    impact_sla_compliance DECIMAL(5,2) DEFAULT 0.00,
    resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    escalation_level INT DEFAULT 0,
    ticks_at_max_escalation INT DEFAULT 0,
    FOREIGN KEY (session_id) REFERENCES game_session(id),
    FOREIGN KEY (basestation_id) REFERENCES basestation(id)
);
